import { Kulim_Park } from "next/font/google";
import "./globals.scss";
import "bulma/css/bulma.css";
import "@/styles/btn.css";
import StickyCursor from "@/components/cube/stickyCursor";
const inter = Kulim_Park({ subsets: ["latin"], weight: "400" });

const metadata = {
  title: "CYAN - frontend portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="h-screen
    "
    >
      <head>
        {" "}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={inter.className}>
        {" "}
        <StickyCursor /> {children}
      </body>
    </html>
  );
}
